version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      reliability-kit:
        patterns:
          - "@dotcom-reliability-kit/*"
        update-types:
          - "minor"
          - "patch"
